In [8]:
import pandas as pd
import numpy as np

In [6]:
%reset -f

In [9]:
np.random.seed(1234)
base = np.random.rand(6, 3)  # 6 rows of 3 dimensional vectors
base_first_column = [f'Base-{i}' for i in np.arange(6)]
base = pd.DataFrame(base)
base.insert(0, 'id', base_first_column)

I = np.random.randint(6, size=(2, 5))  # ndarray of the shape (2, 5)

train = np.random.rand(2, 3)  # 2 rows of 3 dimensional vectors
train_index = [f'Query-{i}' for i in np.arange(2)]
train = pd.DataFrame(train)
train.insert(0, 'id', train_index)
train['Target'] = base.sample(2, random_state=1234)['id'].values

train_target = train['Target']
train_features = train.drop('Target', axis=1)

train_tiled = np.tile(train.values, 5).reshape(2, 5, 5)  # tiled (repeated) rows in train

I_flat = I.ravel()  # flatten I
result_values = base.values[I_flat]  # take only those from base that are in flatten
new_I = result_values.reshape(2, 5, 4)  # create new 3d array

# Check if the last values of axis=2 in 'train_tiled' are equal to the last values of axis=2 in 'new_I'
last_values_equal = np.equal(train_tiled[..., -1], new_I[..., 0])

# Add a new axis with values 1 or 0 depending on 'last_values_equal' - to make it 3d
new_axis = np.expand_dims(last_values_equal.astype(int), axis=2)

# Concatenate the two arrays on axis=2 along with the new axis
train_final = np.concatenate([train_tiled[..., :-1], new_I[..., 1:], new_axis], axis=2)

In [10]:
train_final.shape

(2, 5, 8)

In [17]:
train_final = train_final.reshape(10, 8)

In [21]:
train_final_df = pd.DataFrame(train_final)
train_final_df

0        1         2         3         4         5         6  7
0  Query-0  0.93314  0.651378  0.397203  0.276464  0.801872  0.958139  1
1  Query-0  0.93314  0.651378  0.397203  0.276464  0.801872  0.958139  1
2  Query-0  0.93314  0.651378  0.397203  0.875933  0.357817  0.500995  0
3  Query-0  0.93314  0.651378  0.397203  0.875933  0.357817  0.500995  0
4  Query-0  0.93314  0.651378  0.397203  0.191519  0.622109  0.437728  0
5  Query-1  0.78873  0.316836  0.568099  0.785359  0.779976  0.272593  1
6  Query-1  0.78873  0.316836  0.568099  0.875933  0.357817  0.500995  0
7  Query-1  0.78873  0.316836  0.568099  0.191519  0.622109  0.437728  0
8  Query-1  0.78873  0.316836  0.568099  0.875933  0.357817  0.500995  0
9  Query-1  0.78873  0.316836  0.568099  0.276464  0.801872  0.958139  0

In [25]:
np.average(train_final[:, -1])

0.3

In [27]:
train_final[..., -1]

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0], dtype=object)

In [20]:
y = train_final[:, -1]
y


array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0], dtype=object)

In [201]:
train_final

array([[['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.2764642551430967, 0.8018721775350193,
         0.9581393536837052, 1],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.2764642551430967, 0.8018721775350193,
         0.9581393536837052, 1],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.8759326347420947, 0.35781726995786667,
         0.5009951255234587, 0],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.8759326347420947, 0.35781726995786667,
         0.5009951255234587, 0],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.1915194503788923, 0.6221087710398319,
         0.4377277390071145, 0]],

       [['Query-1', 0.7887301429407455, 0.31683612216887125,
         0.5680986526260692, 0.7853585837137692, 0.7799758081188035,
         0.2725926052826416, 1],
        ['Query-1', 0.7

In [113]:
result_values_reshaped.shape

(2, 5, 4)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(train_features, train_target, train_size=0.5, random_state=42)

/Users/basangbasangov/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [180]:
train3 = np.concatenate((train_tiled[:, :, :-1], new_I[:, :, 1:]), axis=2)
train3

array([[['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.2764642551430967, 0.8018721775350193,
         0.9581393536837052],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.2764642551430967, 0.8018721775350193,
         0.9581393536837052],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.8759326347420947, 0.35781726995786667,
         0.5009951255234587],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.8759326347420947, 0.35781726995786667,
         0.5009951255234587],
        ['Query-0', 0.9331401019825216, 0.6513781432265774,
         0.3972025777261542, 0.1915194503788923, 0.6221087710398319,
         0.4377277390071145]],

       [['Query-1', 0.7887301429407455, 0.31683612216887125,
         0.5680986526260692, 0.7853585837137692, 0.7799758081188035,
         0.2725926052826416],
        ['Query-1', 0.7887301429407455, 0

In [182]:
new_I[..., 0]

array([['Base-2', 'Base-2', 'Base-3', 'Base-3', 'Base-0'],
       ['Base-1', 'Base-3', 'Base-0', 'Base-3', 'Base-2']], dtype=object)

In [145]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [161]:
# (2, 5, 3)
a = np.arange(1, 31)
a = a.reshape(2, 5, 3)

b = np.arange(1, 31)
b = b.reshape(2, 5, 3)
c = np.concatenate((a, b), axis=2)
print(c.shape)
print(c)

(2, 5, 6)
[[[ 1  2  3  1  2  3]
  [ 4  5  6  4  5  6]
  [ 7  8  9  7  8  9]
  [10 11 12 10 11 12]
  [13 14 15 13 14 15]]

 [[16 17 18 16 17 18]
  [19 20 21 19 20 21]
  [22 23 24 22 23 24]
  [25 26 27 25 26 27]
  [28 29 30 28 29 30]]]


In [156]:
a.shape

(2, 5, 3)

In [148]:
b.shape

(1, 2)

In [164]:
# Assuming 'arr1' and 'arr2' are your two 3-dimensional numpy arrays

# Check if the last values of axis=2 in 'arr1' are equal to the last values of axis=2 in 'arr2'
last_values_equal = np.equal(a[..., -1], b[..., -1])

# Add a new axis with values 1 or 0 depending on 'last_values_equal'
new_axis = np.expand_dims(last_values_equal.astype(int), axis=2)

# Concatenate the two arrays on axis=2 along with the new axis
combined_array = np.concatenate([a, b, new_axis], axis=2)

In [165]:
combined_array

array([[[ 1,  2,  3,  1,  2,  3,  1],
        [ 4,  5,  6,  4,  5,  6,  1],
        [ 7,  8,  9,  7,  8,  9,  1],
        [10, 11, 12, 10, 11, 12,  1],
        [13, 14, 15, 13, 14, 15,  1]],

       [[16, 17, 18, 16, 17, 18,  1],
        [19, 20, 21, 19, 20, 21,  1],
        [22, 23, 24, 22, 23, 24,  1],
        [25, 26, 27, 25, 26, 27,  1],
        [28, 29, 30, 28, 29, 30,  1]]])

In [166]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]])

In [167]:
a[..., -1]

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30]])